server:
  port: 49999

spring:
  r2dbc:
    url: ${AUTH_DATABASE_URL:r2dbc:postgresql://localhost:5437/auth_db}
    username: ${DATABASE_USERNAME:restaurant_user}
    password: ${DATABASE_PASSWORD:restaurant_pass}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: docs-page
          uri: http://localhost:49999
          predicates:
            - Path=/docs
          filters:
            - RewritePath=/docs, /swagger-ui.html
        # Order Service routes with /order prefix
        - id: order-service-prefixed
          uri: lb://order-service
          predicates:
            - Path=/order/api/**
          filters:
            - RewritePath=/order/api/(?<segment>.*), /api/$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**, /api/tables/**, /api/employees/**
        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/order-service/api-docs
          filters:
            - RewritePath=/order-service/api-docs, /api-docs
        # Kitchen Service routes with /kitchen prefix
        - id: kitchen-service-prefixed
          uri: lb://kitchen-service
          predicates:
            - Path=/kitchen/api/**
          filters:
            - RewritePath=/kitchen/api/(?<segment>.*), /api/$\{segment}
        - id: kitchen-service
          uri: lb://kitchen-service
          predicates:
            - Path=/api/kitchen/**
        - id: kitchen-service-docs
          uri: lb://kitchen-service
          predicates:
            - Path=/kitchen-service/api-docs
          filters:
            - RewritePath=/kitchen-service/api-docs, /api-docs
        # Menu Service routes with /menu prefix
        - id: menu-service-prefixed
          uri: lb://menu-service
          predicates:
            - Path=/menu/api/**
          filters:
            - RewritePath=/menu/api/(?<segment>.*), /api/$\{segment}
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menu/**, /api/dishes/**, /api/categories/**, /api/ingredients/**
        - id: menu-service-docs
          uri: lb://menu-service
          predicates:
            - Path=/menu-service/api-docs
          filters:
            - RewritePath=/menu-service/api-docs, /api-docs
        # Inventory Service routes with /inventory prefix
        - id: inventory-service-prefixed
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/api/**
          filters:
            - RewritePath=/inventory/api/(?<segment>.*), /api/$\{segment}
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**, /api/ingredients/**, /api/suppliers/**
        - id: inventory-service-docs
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/api-docs
          filters:
            - RewritePath=/inventory-service/api-docs, /api-docs
        # Billing Service routes with /billing prefix
        - id: billing-service-prefixed
          uri: lb://billing-service
          predicates:
            - Path=/billing/api/**
          filters:
            - RewritePath=/billing/api/(?<segment>.*), /api/$\{segment}
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/bills/**
        - id: billing-service-docs
          uri: lb://billing-service
          predicates:
            - Path=/billing-service/api-docs
          filters:
            - RewritePath=/billing-service/api-docs, /api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGp3dCBzZWNyZXQga2V5IGZvciByZXN0YXVyYW50IG1hbmFnZW1lbnQ=}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Authentication
        url: /v3/api-docs
      - name: Order Service
        url: /order-service/api-docs
      - name: Kitchen Service
        url: /kitchen-service/api-docs
      - name: Menu Service
        url: /menu-service/api-docs
      - name: Inventory Service
        url: /inventory-service/api-docs
      - name: Billing Service
        url: /billing-service/api-docs
    urls-primary-name: Authentication
