server:
  port: 0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://file-db:5432/file_db}
    username: ${DATABASE_USERNAME:restaurant_user}
    password: ${DATABASE_PASSWORD:restaurant_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# MinIO configuration for production
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket: ${MINIO_BUCKET:dish-images}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
