server:
  port: 0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5438/file_db}
    username: ${DATABASE_USERNAME:restaurant_user}
    password: ${DATABASE_PASSWORD:restaurant_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# MinIO configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket: ${MINIO_BUCKET:dish-images}

springdoc:
  swagger-ui:
    operationsSorter: method
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
